config/routes.rb
App0521::Application.routes.draw do
 
 
  resources :tasks

  resources :menu_items

  resources :s3_files

  resources :unwanted_cities

  resources :unused_listings

 devise_for :users
 
  #Unused classes=========================   
  #resources :businesses

  #resources :addresses

  #resources :images
  #====================================
  
  #Trying to use Prawn for PDF view
  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  
  #Commented out by Ash as we donot have a Users controller 
  #Devise has an implicit User controller
  #users must always be below devise_for call in the routes file
  
  resources :users
  
  #Commented by Ash in order to let users be editable, if we were using the Devise provided users controller we would use the following
  #resources :users , :only => [:show, :index] 
  
  #Ensure that resources :listings is ALWAYS below devise_for:users and 
  #also below  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  resources :listings
  
  #just resources :assets was causing problems because rails assets has a fixed route.
  #The following workaround works so that "s3_assets_path" should work instead of just "assets_path"
  #resources :assets, :path=>'s3_assets', :as=>'s3_assets'
   #this route is for file downloads
  #match "s3_assets/get/:id" => "s3_assets#get", :as => :download
  
  
  
  #If you examine this code, you’ll see that authenticated users 
  #(those who have an account and are logged in) will see the home/index page as the application root 
  #(or home) page. And all other users (those who don’t have an account or who are not logged in) 
  #will see the same home page. The redundancy serves a didactic purpose: 
  #If you decide you want users to see a different page when they log in, 
  #you now know exactly where to change it.
  authenticated :user do
    root :to => "listings#index"
  end
  root :to => "listings#index"
  
  #For map view
  match "/geoView" => "listings#geoView", :as => :geoView
  
  #For Admin Tasks run method
  match "tasks/run/:id" => "tasks#run", :as => :run_tasks
  
  
   #added by Ash- admin dashboard does not need to be added, deleted or edited
  resources :admin_dash_board,  :only => :index

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id                    :integer         not null, primary key
#  name                  :string(255)     default("Not Available")
#  telephone             :string(255)     default("Not Available")
#  fax                   :string(255)     default("Not Available")
#  suite                 :string(255)     default("Not Available")
#  address               :string(255)     default("Not Available")
#  city                  :string(255)     default("Not Available")
#  province              :string(255)     default("Not Available")
#  postal_code           :string(255)     default("Not Available")
#  latitude              :string(255)     default("Not Available")
#  longitude             :string(255)     default("Not Available")
#  business_type         :string(255)     default("Not Available")
#  sub_type              :string(255)     default("Not Available")
#  owner                 :string(255)     default("Not Available")
#  source                :string(255)     default("Not Available")
#  local_area            :string(255)     default("Not Available")
#  created_at            :datetime        not null
#  updated_at            :datetime        not null
#  checked               :boolean
#  menu_collected        :boolean
#  menu_digitized        :boolean
#  menu_in_database      :boolean
#  keep                  :boolean         default(TRUE)
#  get_menu_from_website :boolean         default(TRUE)
#  notes                 :text
#  menu_state            :string(255)
#  menu_source           :string(255)
#

class Listing < ActiveRecord::Base
  

  #NON DATATABLES VERSION uses this===============
  
  #def self.search(search)
   # if search
    #  where(['name LIKE ?', "%#{search}"])
    #else
     # scoped
   
    #end
  
#end


=begin
  has_attached_file :image,
                    :styles =>
                    {
                      :thumb => "75x75>", :small => "150x150>", 
                      :medium => "300x300>"
                    }
                    :storage => :s3,
                    :bucket => ENV['S3_BUCKET_NAME'],
                    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
=end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user! 
  
  helper_method :sort_column, :sort_direction
=begin  
  def get_all
    @temp_listings = TempListing.order("name ASC")
  end
  
  def create_listings_from_temp_listings
    self.get_all
    @temp_listings.each do|temp_listing|
      
      @listing = Listing.new()
      @listing.name = temp_listing.name
      @listing.telephone = temp_listing.telephone
      @listing.fax = temp_listing.fax
      @listing.suite = temp_listing.suite
      @listing.address = temp_listing.address
      @listing.city = temp_listing.city
      @listing.province = temp_listing.province
      @listing.postal_code = temp_listing.postal_code
      @listing.latitude = temp_listing.latitude
      @listing.longitude = temp_listing.longitude
      @listing.businessType = temp_listing.businessType
      @listing.subType = temp_listing.subType
      @listing.owner = temp_listing.owner
      @listing.source = temp_listing.source
      @listing.localArea = temp_listing.localArea
            
      @listing.save
      
    end
  end
  

  def create_listings_from_addresses
    @addresses = Address.order("business_name ASC")
    @addresses.each do|address|
      @listing = Listing.new()
      @listing.name = address.business_name
      @listing.telephone = address.telephone_1
      @listing.fax = address.fax
      @listing.suite = "YP"
      @listing.address = address.address
      @listing.city = address.city
      @listing.province = "BC"
      @listing.postal_code = "YP"
      @listing.latitude = nil
      @listing.longitude = nil
      @listing.business_type = "YP"
      @listing.sub_type = "YP"
      @listing.owner = "YP"
      @listing.source = "Leah's yellow pages goodies ;-)"
      @listing.local_area = "YP"
      @listing.menu_collected = nil
      @listing.menu_digitized = nil
      @listing.menu_in_database = nil
      @listing.keep = true
      @listing.get_menu_from_website = nil
      @listing.notes = "Secondary Phone: #{address.telephone_2}"
      @listing.menu_state = nil
      @listing.menu_source = "not_applicable"
                  
      @listing.save
      
    end
  end
=end 
#==============================================================================
 #Get unwanted listings from listings table
 def create_unwanted_listings_from_city
    #@listings = Listing.where("city != ?").order("name ASC").order("address ASC")
    @listings.each do|listing|
      @unwanted_city = UnwantedCity.new()
      @unwanted_city.name = listing.name
      @unwanted_city.telephone = listing.telephone
      @unwanted_city.fax = listing.fax
      @unwanted_city.suite = listing.suite
      @unwanted_city.address = listing.address
      @unwanted_city.city = listing.city
      @unwanted_city.province = listing.province
      @unwanted_city.postal_code = listing.postal_code
      @unwanted_city.latitude = listing.latitude
      @unwanted_city.longitude = listing.longitude
      @unwanted_city.business_type = listing.business_type
      @unwanted_city.sub_type = listing.sub_type
      @unwanted_city.owner = listing.owner
      @unwanted_city.source = listing.source
      @unwanted_city.local_area = listing.local_area
      @unwanted_city.checked =listing.checked
      @unwanted_city.menu_collected = listing.menu_collected 
      @unwanted_city.menu_digitized = listing.menu_digitized
      @unwanted_city.menu_in_database = listing.menu_in_database
      @unwanted_city.keep = listing.keep
      @unwanted_city.get_menu_from_website = listing.get_menu_from_website
      @unwanted_city.notes = listing.notes
      @unwanted_city.menu_state = listing.menu_state
      @unwanted_city.menu_source = listing.menu_source
                  
      @unwanted_city.save
      
    end
  end
  
  
  
  
  
#==============================================================================
  def geoView
    
    #self.create_listings_from_addresses
    #render :text=>(@listings).to_json()
    #render :json =>@listings
    respond_to do |format|
         format.html do#list.html.erb
           @listings = Listing.all
         end
          @listings = Listing.all
         format.json {render :json =>@listings}
     end
  end
#============NON DATATABLES VERSION OF INDEX================================================  
=begin
  def index
    
    #@listings = Listing.order(params[:sort] + " " +  params[:direction])
    @listings = Listing.search(params[:search]).order(sort_column + " " +  sort_direction ).paginate(:per_page => 20, :page => params[:page])
    #respond_to do |format|
     # format.html # index.html.erb
      #format.json { render json: @listing }
    #end
  end
=end
#======DATATABLES VERSION OF INDEX METHOD
 # GET /listings
  # GET /listings.json
  def index
    #self.create_listings_from_temp_listings
    
    respond_to do |format|
      format.html do# index.html.erb
        @listings = Listing.all
        #@listings = Listing.where(:keep => false)
      end
      format.json { render json: ListingsDatatable.new(view_context) } 
      #format.pdf do 
        #pdf = Prawn::Document.new
        #pdf.text "Hello World"
        #send_data pdf.render, filename: "listings.pdf", type: "application/pdf", disposition: "inline"
      #end
      
    end
  end
#=============================================

  # GET /listings/1
  # GET /listings/1.json
  def show
    respond_to do |format|
      format.html do # show.html.erb
       @listing = Listing.find(params[:id]) 
      end
      format.json { render json: @listing }
      #format.pdf do 
        #pdf = Prawn::Document.new
        #pdf.text "Hello World"
        #send_data pdf.render
      #end
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])
    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        #format.html { redirect_to listings_url , notice: 'Listing was successfully updated.'}
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
        #format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end
  
  def show_notes
    #@listings = Listing.where("listings.notes IS NOT NULL").order("listings.name ASC")
    @listings = Listing.where("listings.menu_state = 'collect_from_location' OR listings.menu_state = 'outside_downtown'").order("listings.name ASC")
    #@listings = Listing.order("listings.menu_state").order("listings.menu_source")
    #@listings = Listing.all
    #@listings = Listing.order("listings.name ASC")
    #@listings = Listing.where('menu_state <> ?', "not_a_restaurant").where('menu_state <> ?',"collected").where('menu_state <> ?',"digitized").where('menu_state <> ?',"pending")


    #@listings = Listing.order('listings.menu_state ASC').order("listings.name ASC")
    respond_to do |format|
        format.pdf do
        #pdf = Prawn::Document.new
        pdf = ListingsNotes.new(@listings)

        send_data pdf.render, filename: "listings_notes.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
  
  
  
  private
  #used by non datatables index
  def sort_column
    Listing.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%if user_signed_in? %></br/>

<%= simple_form_for(@listing, :html => {:multipart => true, :class=> 'form-horizontal'} ) do |f| %>
  <%= f.error_notification %>
   <%= f.button :submit %>
  
  <%= f.input :id , :readonly => true %>
  <%= f.input :name %>
  <%= f.input :checked , hint: "Has the data been cleansed and checked?" %>
  <%= f.input :menu_state,  collection: [:sent_to_India, :converted_to_Excel, :cleansed, :tagged, :inserted_in_DB, :not_collected, :not_a_restaurant, :refused_to_give, :outside_downtown, :collect_from_location, :collect_from_outside_DT] %>
  <%= f.input :menu_source, collection: [:text, :website, :raw, :not_applicable ] %>
  
  <%= f.input :keep , hint: "After checking for duplicates decide whether to keep or flag as a duplicate.."%>
  <%= f.input :notes, hint: "Further instructions on what needs to be done" %>
  <%= f.input :telephone %>
  <%= f.input :fax %>
  <%= f.input :suite %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :province %>
  <%= f.input :postal_code %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.input :business_type %>
  <%= f.input :sub_type %>
  <%= f.input :owner %>
  <%= f.input :local_area %>
  <%= f.error :base %>
  
 
  
  
<% end %>
<%else%>
				<%=link_to "Sign in", new_user_session_path , :class => 'btn btn-mini btn-danger'%><br/>
					Contact the admin to obtain a login and password
<%end%>

app/views/listings/edit.html.erb
<div class = "well">
<%= render 'form' %>
</div>

app/views/listings/geoView.html.erb
<!--<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />-->

<!--<%= stylesheet_link_tag 'application' %>-->
<!--<%= javascript_include_tag  'geoView'%>-->
<!--<%= javascript_include_tag  'application'%>-->
<body onload="initialize()">

	<div id="top_vendors" class="scroll-pane ui-widget ui-widget-header ui-corner-all">
	<div class="scroll-content-item ui-widget-header">1</div>
		<div class="scroll-content-item ui-widget-header">2</div>
		<div class="scroll-content-item ui-widget-header">3</div>
		<div class="scroll-content-item ui-widget-header">4</div>
		<div class="scroll-content-item ui-widget-header">5</div>
		<div class="scroll-content-item ui-widget-header">6</div>
		<div class="scroll-content-item ui-widget-header">7</div>
		<div class="scroll-content-item ui-widget-header">8</div>
		<div class="scroll-content-item ui-widget-header">9</div>
		<div class="scroll-content-item ui-widget-header">10</div>
		<div class="scroll-content-item ui-widget-header">11</div>
		<div class="scroll-content-item ui-widget-header">12</div>
		<div class="scroll-content-item ui-widget-header">13</div>
		<div class="scroll-content-item ui-widget-header">14</div>
		<div class="scroll-content-item ui-widget-header">15</div>
		<div class="scroll-content-item ui-widget-header">16</div>
		<div class="scroll-content-item ui-widget-header">17</div>
		<div class="scroll-content-item ui-widget-header">18</div>
		<div class="scroll-content-item ui-widget-header">19</div>
		<div class="scroll-content-item ui-widget-header">20</div>
		
		
		
	
		</div>
		<div class="scroll-bar-wrap ui-widget-content ui-corner-bottom">
		<div class="scroll-bar"></div>
	</div>
	
		<div id="left_control_panel" class="button_panel">
			<input type="button" id="b1", onclick="getlistings();" value="Add Markers" >
			<input type="button" onclick="clearMarkers();" value="Remove Markers">
		</div>
	
	
	<div id="mid_wrapper">
		<div id="map_canvas"></div>
			<div id="right_control_panel">
				<input type="button" onclick="getlistings();" value="Add Markers">
				<input type="button" onclick="clearMarkers();" value="Remove Markers">
                <p id="info"></p>
			</div>
		</div>
	</div>




</body>

<script type="text/javascript"
src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAcCH7ntWPihR8rdCsblUiSRSNptYsO6IA&sensor=false"></script>

app/views/listings/index.html.erb
<b><%= link_to 'New Listing', new_listing_path , :class => 'btn btn-warning'%></b> 
<b><%= link_to 'Printable List: Listings name + notes', show_notes_path(format: "pdf") , :class => 'btn btn-warning'%></b>

<table id="listings" class="display" data-source="<%= listings_url(format: "json")%>">
	<thead>
  <tr>
  	<th>id</th>
    <th>name</th>
  	<th>Checked?</th>
  	<th>Menu State</th>
    <th>Menu Source</th>
    <th>Keep this listing?</th>
    <th>notes</th>
    <th>telephone</th>
    <th>fax</th>
    <th>suite</th>
    <th>address</th>
    <th>city</th>
    <th>province</th>
    <th>postal code</th>
    <th>latitude</th>
    <th>longitude</th>
    <th>business type</th>
    <th>sub type</th>
    <th>Owner</th>
    <th>Local area</th>
    
  </tr>
	</thead>
	
	<tbody>

	</tbody>
</table>

<br />

app/views/listings/new.html.erb
<h1>New listing</h1>
<div class = "well">
<%= render 'form' %>
</div>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= link_to 'Edit this listing', edit_listing_path(@listing), :class => 'btn btn-warning' %> </p>

<div class="well">
<p><b>[<%= @listing.id %> ] <%= @listing.name %></b></p>

</div>

<div class="well">	
<p><b>Listing info Checked?:</b><%= @listing.checked %></p>
<p><b>Menu State:</b><%= @listing.menu_state %></p>
<p><b>Menu Source:</b><%= @listing.menu_source %></p>
<p><b>Keep listing:</b><%= @listing.keep %></p>
</div>
<div class="well">
<p><b>Notes:</b><%= @listing.notes %></p>
<p><b>telephone:</b><%= @listing.telephone %></p>
<p><b>fax:</b><%= @listing.fax %></p>
<p><b>suite:</b><%= @listing.suite %></p>
<p><b>address:</b><%= @listing.address %></p>
<p><b>city:</b><%= @listing.city %></p>
<p><b>province:</b><%= @listing.province %></p>
<p><b>postal_code:</b><%= @listing.postal_code %></p>
<p><b>latitude:</b><%= @listing.latitude %></p>
<p><b>longitude:</b><%= @listing.longitude %></p>
<p><b>business_type:</b><%= @listing.business_type %></p>
<p><b>sub_type:</b><%= @listing.sub_type %></p>
<p><b>owner:</b><%= @listing.owner %></p>
<p><b>localArea:</b><%= @listing.local_area %></p>
</div>