config/routes.rb
App0521::Application.routes.draw do
 
 
  resources :tasks

  resources :menu_items

  resources :s3_files

  resources :unwanted_cities

  resources :unused_listings

 devise_for :users
 
  #Unused classes=========================   
  #resources :businesses

  #resources :addresses

  #resources :images
  #====================================
  
  #Trying to use Prawn for PDF view
  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  
  #Commented out by Ash as we donot have a Users controller 
  #Devise has an implicit User controller
  #users must always be below devise_for call in the routes file
  
  resources :users
  
  #Commented by Ash in order to let users be editable, if we were using the Devise provided users controller we would use the following
  #resources :users , :only => [:show, :index] 
  
  #Ensure that resources :listings is ALWAYS below devise_for:users and 
  #also below  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  resources :listings
  
  #just resources :assets was causing problems because rails assets has a fixed route.
  #The following workaround works so that "s3_assets_path" should work instead of just "assets_path"
  #resources :assets, :path=>'s3_assets', :as=>'s3_assets'
   #this route is for file downloads
  #match "s3_assets/get/:id" => "s3_assets#get", :as => :download
  
  
  
  #If you examine this code, you’ll see that authenticated users 
  #(those who have an account and are logged in) will see the home/index page as the application root 
  #(or home) page. And all other users (those who don’t have an account or who are not logged in) 
  #will see the same home page. The redundancy serves a didactic purpose: 
  #If you decide you want users to see a different page when they log in, 
  #you now know exactly where to change it.
  authenticated :user do
    root :to => "listings#index"
  end
  root :to => "listings#index"
  
  #For map view
  match "/geoView" => "listings#geoView", :as => :geoView
  
  #For Admin Tasks run method
  match "tasks/run/:id" => "tasks#run", :as => :run_tasks
  
  
   #added by Ash- admin dashboard does not need to be added, deleted or edited
  resources :admin_dash_board,  :only => :index

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id                   :integer         not null, primary key
#  last_run_at_time     :string(255)
#  created_at           :datetime        not null
#  updated_at           :datetime        not null
#  description          :text
#  task_name            :string(255)
#  last_run_by_user     :string(255)
#  output_from_last_run :text
#

class Task < ActiveRecord::Base
  include TasksHelper

  #include ActionView::Helpers
  #ActionController::Base.helpers.sanitize(str)

  #All the tasks invoked in the following method are defined in the helpers/tasks_helper module
  def run_task(user_id)
    @usr = User.find(user_id)
    case self.task_name

      when "menu_state_count"
        self.description = "menu_state_count ran at #{Time.now} by #{@usr.email}"
        self.output_from_last_run = menu_state_count
      when "read_csv_net_http"
        self.description = "read_csv_net_http ran at #{Time.now} by #{@usr.email}"
        self.output_from_last_run = read_csv_net_http
      when "read_csv_open_uri"
        self.description = "read_csv_open_uri ran at #{Time.now} by #{@usr.email}"
        self.output_from_last_run = read_csv_open_uri
      when "copy_dupes_from_listings"
        self.description = "copy_dupes_from_listings ran at #{Time.now} by #{@usr.email}"
        self.output_from_last_run = copy_dupes_from_listings
      when "remove_dupes_from_listings"
        self.description = "remove_dupes_from_listings ran at #{Time.now} by #{@usr.email}"
        self.output_from_last_run = remove_dupes_from_listings
      when "set_menu_state"
        self.description = "set_menu_state ran at #{Time.now} by #{@usr.email}"
        self.output_from_last_run = set_menu_state
      else
        self.description = "<ERROR> ran at #{Time.now} User = #{@usr.email}"
        self.output_from_last_run = "<ERROR>#{Time.now} User = #{@usr.email}"

    end

    self.save
  end






end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :authenticate_user!


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end




  def run
    @task = Task.find(params[:id])
    @curr_user = User.find(current_user.id)
    @task.run_task(@curr_user)

    respond_to do |format|
      format.html
      format.json
    end

  end




end

app/helpers/tasks_helper.rb
module TasksHelper
  #Define all tasks here that will be used by the Task module
  @buffer = ""
  def  menu_state_count
    @buffer = "\n\nThe following is the count of all the state of the menus for each listing\n\n"

    @listings = Listing.all.count
    @buffer << "Total Listings = #{@listings} \n"

    @sent_to_India = Listing.where("listings.menu_state = 'sent_to_India' " ).count
    @buffer <<  "Sent to India = #{@sent_to_India} \n"
    @converted_to_Excel = Listing.where("listings.menu_state = 'converted_to_Excel' " ).count
    @buffer << "Converted to Excel = #{@converted_to_Excel} \n"
    @cleansed = Listing.where("listings.menu_state = 'cleansed' " ).count
    @buffer << "Cleansed = #{@cleansed} \n"
    @tagged = Listing.where("listings.menu_state = 'tagged' " ).count
    @buffer << "Tagged = #{@tagged} \n"
    @inserted_in_DB = Listing.where("listings.menu_state = 'inserted_in_DB' " ).count
    @buffer << "Inserted into db = #{@inserted_in_DB} \n"
    @not_collected = Listing.where("listings.menu_state = 'not_collected' " ).count
    @buffer << "Not Collected = #{@not_collected} \n"
    @not_a_restaurant = Listing.where("listings.menu_state = 'not_a_restaurant' " ).count
    @buffer << "not_a_restaurant = #{@not_a_restaurant} \n"
    @refused_to_give = Listing.where("listings.menu_state = 'refused_to_give' " ).count
    @buffer << "Refused to give = #{@refused_to_give} \n"
    @outside_downtown = Listing.where("listings.menu_state = 'outside_downtown' " ).count
    @buffer << "Outside Downtown = #{@outside_downtown} \n"
    @collect_from_location = Listing.where("listings.menu_state = 'collect_from_location' " ).count
    @buffer << "collect_from_location = #{@collect_from_location} \n"
    @collect_from_outside_DT = Listing.where("listings.menu_state = 'collect_from_outside_DT' " ).count
    @buffer << "collect_from_outside_DT = #{@collect_from_outside_DT} \n"
    @invalid_with_space = Listing.where("listings.menu_state = '' " ).count
    @buffer << "Invalid with \"\" = #{@invalid_with_space} \n"
    @invalid_with_spaces = Listing.where("listings.menu_state = ' ' " ).count
    @buffer << "Invalid with \" \" = #{@invalid_with_spaces} \n"
    @invalid_with_null = Listing.where("listings.menu_state IS null" ).count
    @buffer << "Invalid with null = #{@invalid_with_null} \n"

  end

  def read_csv_net_http
    @buffer = "From Tasks Helper read_csv_net_http #{Time.now}"
    @buffer << "Testing <<"
  end

  def read_csv_open_uri
    @buffer = "From Tasks Helper read_csv_net_http #{Time.now}"
    @buffer << "Testing <<"
  end

  def copy_dupes_from_listings
    @buffer = "From Tasks Helper copy_dupes_from_listings #{Time.now}"
    @buffer << "Testing <<"
  end

  def remove_dupes_from_listings
    @buffer = "From Tasks Helper remove_dupes_from_listings#{Time.now}"
    @buffer << "Testing <<"
  end

  def set_menu_state
    @buffer = "From Tasks Helper set_menu_state#{Time.now}"
    @buffer << "Testing <<"
  end



end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :task_name, collection: [:menu_state_count, :set_menu_state, :copy_dupes_from_listings, :remove_dupes_from_listings, :read_csv_net_http, :read_csv_open_uri] %>
  </div>

    <div class="form-inputs">
      <%= f.input :description %>
    </div>


    <div class="form-inputs">
      <%= f.input :last_run_at_time %>
    </div>

    <div class="form-inputs">
      <%= f.input :last_run_by_user %>
    </div>

    <div class="form-inputs">
      <%= f.input :output_from_last_run %>
    </div>



  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table>
  <tr>
    <th>Task Name</th>
    <th>Description</th>
    <th>Last Run at</th>
    <th>Last Run by</th>

  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%=task.task_name %></td>
    <td><%=task.description %></td>
    <td><%=task.last_run_at_time %></td>
    <td><%=task.last_run_by_user %></td>

    <td><%= link_to 'Run Task now', run_tasks_path(task)  %></td>
    <td><%= link_to 'Last Times output', task %></td>
   <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/run.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task id:</b>
  <%= @task.id %>
</p>
<p>
  <b>Task name:</b>
  <%= @task.task_name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Last Run at:</b>
  <%= @task.last_run_at_time %>
</p>

<p>
  <b>Last Run by:</b>
  <%= @task.last_run_by_user %>
</p>

<p>
  <b>Output from last run:</b>
  <%= h(@task.output_from_last_run).gsub(/\n/, '<br/>' ).html_safe %>
</p>






<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task id:</b>
  <%= @task.id %>
</p>
<p>
  <b>Task name:</b>
  <%= @task.task_name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Last Run at:</b>
  <%= @task.last_run_at_time %>
</p>

<p>
  <b>Last Run by:</b>
  <%= @task.last_run_by_user %>
</p>

<p>
  <b>Output from last run:</b>
  <%= h(@task.output_from_last_run).gsub(/\n/, '<br/>' ).html_safe  %>
</p>





<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>