config/routes.rb
App0521::Application.routes.draw do
 
 
  resources :tasks

  resources :menu_items

  resources :s3_files

  resources :unwanted_cities

  resources :unused_listings

 devise_for :users
 
  #Unused classes=========================   
  #resources :businesses

  #resources :addresses

  #resources :images
  #====================================
  
  #Trying to use Prawn for PDF view
  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  
  #Commented out by Ash as we donot have a Users controller 
  #Devise has an implicit User controller
  #users must always be below devise_for call in the routes file
  
  resources :users
  
  #Commented by Ash in order to let users be editable, if we were using the Devise provided users controller we would use the following
  #resources :users , :only => [:show, :index] 
  
  #Ensure that resources :listings is ALWAYS below devise_for:users and 
  #also below  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  resources :listings
  
  #just resources :assets was causing problems because rails assets has a fixed route.
  #The following workaround works so that "s3_assets_path" should work instead of just "assets_path"
  #resources :assets, :path=>'s3_assets', :as=>'s3_assets'
   #this route is for file downloads
  #match "s3_assets/get/:id" => "s3_assets#get", :as => :download
  
  
  
  #If you examine this code, you’ll see that authenticated users 
  #(those who have an account and are logged in) will see the home/index page as the application root 
  #(or home) page. And all other users (those who don’t have an account or who are not logged in) 
  #will see the same home page. The redundancy serves a didactic purpose: 
  #If you decide you want users to see a different page when they log in, 
  #you now know exactly where to change it.
  authenticated :user do
    root :to => "listings#index"
  end
  root :to => "listings#index"
  
  #For map view
  match "/geoView" => "listings#geoView", :as => :geoView
  
  #For Admin Tasks run method
  match "tasks/run/:id" => "tasks#run", :as => :run_tasks
  
  
   #added by Ash- admin dashboard does not need to be added, deleted or edited
  resources :admin_dash_board,  :only => :index

end

app/models/unwanted_city.rb
# == Schema Information
#
# Table name: unwanted_cities
#
#  id                    :integer         not null, primary key
#  created_at            :datetime        not null
#  updated_at            :datetime        not null
#  name                  :string(255)
#  telephone             :string(255)
#  fax                   :string(255)
#  suite                 :string(255)
#  address               :string(255)
#  city                  :string(255)
#  province              :string(255)
#  postal_code           :string(255)
#  latitude              :string(255)
#  longitude             :string(255)
#  business_type         :string(255)
#  sub_type              :string(255)
#  owner                 :string(255)
#  source                :string(255)
#  local_area            :string(255)
#  checked               :boolean
#  menu_collected        :boolean
#  menu_digitized        :boolean
#  menu_in_database      :boolean
#  keep                  :boolean
#  get_menu_from_website :boolean
#  notes                 :text
#  menu_state            :string(255)
#  menu_source           :string(255)
#

class UnwantedCity < ActiveRecord::Base
end

app/controllers/unwanted_cities_controller.rb
class UnwantedCitiesController < ApplicationController
  before_filter :authenticate_user! 
  
  def create_unwanted_listings

    @listings = Listing.where(['city != ?', "Vancouver"]).where(['city != ?', " Vancouver"]).where(['city != ?', "Vancouver "])

    @listings.each do|listing|
      @unwanted_city = UnwantedCity.new()
      @unwanted_city.name = listing.name
      @unwanted_city.telephone = listing.telephone
      @unwanted_city.fax = listing.fax
      @unwanted_city.suite = listing.suite
      @unwanted_city.address = listing.address
      @unwanted_city.city = listing.city
      @unwanted_city.province = listing.province
      @unwanted_city.postal_code = listing.postal_code
      @unwanted_city.latitude = listing.latitude
      @unwanted_city.longitude = listing.longitude
      @unwanted_city.business_type = listing.business_type
      @unwanted_city.sub_type = listing.sub_type
      @unwanted_city.owner = listing.owner
      @unwanted_city.source = listing.source
      @unwanted_city.local_area = listing.local_area
      @unwanted_city.checked =listing.checked
      @unwanted_city.menu_collected = listing.menu_collected 
      @unwanted_city.menu_digitized = listing.menu_digitized
      @unwanted_city.menu_in_database = listing.menu_in_database
      @unwanted_city.keep = listing.keep
      @unwanted_city.get_menu_from_website = listing.get_menu_from_website
      @unwanted_city.notes = listing.notes
      @unwanted_city.menu_state = listing.menu_state
      @unwanted_city.menu_source = listing.menu_source
                  
      @unwanted_city.save
    end
  end
  
  # GET /unwanted_cities
  # GET /unwanted_cities.json
  def index
    #self.create_unwanted_listings
    #@unwanted_cities = Listing.where(['city != ?', "Vancouver"]).where(['city != ?', " Vancouver"]).where(['city != ?', "Vancouver "])
    #Listing.where(['city != ?', "Vancouver"]).where(['city != ?', " Vancouver"]).where(['city != ?', "Vancouver "]).each{|r| r.destroy }
    
    @unwanted_cities = UnwantedCity.all
    #UnwantedCity.destroy_all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unwanted_cities }
    end
  end

  # GET /unwanted_cities/1
  # GET /unwanted_cities/1.json
  def show
    @unwanted_city = UnwantedCity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unwanted_city }
    end
  end

  # GET /unwanted_cities/new
  # GET /unwanted_cities/new.json
  def new
    @unwanted_city = UnwantedCity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unwanted_city }
    end
  end

  # GET /unwanted_cities/1/edit
  def edit
    @unwanted_city = UnwantedCity.find(params[:id])
  end

  # POST /unwanted_cities
  # POST /unwanted_cities.json
  def create
    @unwanted_city = UnwantedCity.new(params[:unwanted_city])

    respond_to do |format|
      if @unwanted_city.save
        format.html { redirect_to @unwanted_city, notice: 'Unwanted city was successfully created.' }
        format.json { render json: @unwanted_city, status: :created, location: @unwanted_city }
      else
        format.html { render action: "new" }
        format.json { render json: @unwanted_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unwanted_cities/1
  # PUT /unwanted_cities/1.json
  def update
    @unwanted_city = UnwantedCity.find(params[:id])

    respond_to do |format|
      if @unwanted_city.update_attributes(params[:unwanted_city])
        format.html { redirect_to @unwanted_city, notice: 'Unwanted city was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unwanted_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unwanted_cities/1
  # DELETE /unwanted_cities/1.json
  def destroy
    @unwanted_city = UnwantedCity.find(params[:id])
    @unwanted_city.destroy

    respond_to do |format|
      format.html { redirect_to unwanted_cities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/unwanted_cities_helper.rb
module UnwantedCitiesHelper
end

app/views/unwanted_cities/_form.html.erb
<%= simple_form_for(@unwanted_city) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/unwanted_cities/edit.html.erb
<h1>Editing unwanted_city</h1>

<%= render 'form' %>

<%= link_to 'Show', @unwanted_city %> |
<%= link_to 'Back', unwanted_cities_path %>

app/views/unwanted_cities/index.html.erb
<h1>Listing unwanted_cities</h1>
<!--
<%= @uwcities = UnwantedCity.all %>
<%= @uwcities.inspect%>
-->
<p>There are <%=Listing.all.count %> listings in the database that are Vancouver cities</p>
<p>There are <%=@unwanted_cities.count %> listings in the database that are non Vancouver cities</p>
<table>
  <tr>
    <th>name</th>
    <th>telephone</th>
    <th>fax</th>
    <th>suite</th>
    <th>address</th>
    <th>city</th>
    <th>province</th>
    <th>postal_code</th>
    <th>latitude</th>
    <th>longitude</th>
    <th>business_type</th>
    <th>sub_type</th>
    <th>owner</th>
    <th>source</th>
    <th>local_area</th>
    <th>checked</th>
    <th>menu_collected</th>
    <th>menu_digitized</th>
    <th>menu_in_database</th>
    <th>keep</th>
    <th>get_menu_from_website</th>
    <th>notes</th>
    <th>menu_state</th>
    <th>menu_source</th>
  </tr>

<% @unwanted_cities.each do |unwanted_city| %>
  <tr>
  	<td><%= unwanted_city.name %></td>
  	<td><%= unwanted_city.telephone %></td>
  	<td><%= unwanted_city.fax %></td>
  	<td><%= unwanted_city.suite %></td>
  	<td><%= unwanted_city.address %></td>
  	<td><%= unwanted_city.city %></td>
  	<td><%= unwanted_city.province %></td>
  	<td><%= unwanted_city.postal_code %></td>
  	<td><%= unwanted_city.latitude %></td>
  	<td><%= unwanted_city.longitude %></td>
  	<td><%= unwanted_city.business_type %></td>
  	<td><%= unwanted_city.sub_type %></td>
  	<td><%= unwanted_city.owner %></td>
  	<td><%= unwanted_city.source %></td>
  	<td><%= unwanted_city.local_area %></td>
  	<td><%= unwanted_city.checked %></td>
  	<td><%= unwanted_city.menu_collected %></td>
  	<td><%= unwanted_city.menu_digitized %></td>
  	<td><%= unwanted_city.menu_in_database %></td>
  	<td><%= unwanted_city.keep %></td>
  	<td><%= unwanted_city.get_menu_from_website %></td>
  	<td><%= unwanted_city.notes %></td>
  	<td><%= unwanted_city.menu_state %></td>
  	<td><%= unwanted_city.menu_source %></td>
    <td><%= link_to 'Show', unwanted_city %></td>
    <td><%= link_to 'Edit', edit_unwanted_city_path(unwanted_city) %></td>
    <td><%= link_to 'Destroy', unwanted_city, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unwanted city', new_unwanted_city_path %>

app/views/unwanted_cities/new.html.erb
<h1>New unwanted_city</h1>

<%= render 'form' %>

<%= link_to 'Back', unwanted_cities_path %>

app/views/unwanted_cities/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_unwanted_city_path(@unwanted_city) %> |
<%= link_to 'Back', unwanted_cities_path %>