config/routes.rb
App0521::Application.routes.draw do
 
 
  resources :tasks

  resources :menu_items

  resources :s3_files

  resources :unwanted_cities

  resources :unused_listings

 devise_for :users
 
  #Unused classes=========================   
  #resources :businesses

  #resources :addresses

  #resources :images
  #====================================
  
  #Trying to use Prawn for PDF view
  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  
  #Commented out by Ash as we donot have a Users controller 
  #Devise has an implicit User controller
  #users must always be below devise_for call in the routes file
  
  resources :users
  
  #Commented by Ash in order to let users be editable, if we were using the Devise provided users controller we would use the following
  #resources :users , :only => [:show, :index] 
  
  #Ensure that resources :listings is ALWAYS below devise_for:users and 
  #also below  match "listings/show_notes" => "listings#show_notes", :as => :show_notes
  resources :listings
  
  #just resources :assets was causing problems because rails assets has a fixed route.
  #The following workaround works so that "s3_assets_path" should work instead of just "assets_path"
  #resources :assets, :path=>'s3_assets', :as=>'s3_assets'
   #this route is for file downloads
  #match "s3_assets/get/:id" => "s3_assets#get", :as => :download
  
  
  
  #If you examine this code, you’ll see that authenticated users 
  #(those who have an account and are logged in) will see the home/index page as the application root 
  #(or home) page. And all other users (those who don’t have an account or who are not logged in) 
  #will see the same home page. The redundancy serves a didactic purpose: 
  #If you decide you want users to see a different page when they log in, 
  #you now know exactly where to change it.
  authenticated :user do
    root :to => "listings#index"
  end
  root :to => "listings#index"
  
  #For map view
  match "/geoView" => "listings#geoView", :as => :geoView
  
  #For Admin Tasks run method
  match "tasks/run/:id" => "tasks#run", :as => :run_tasks
  
  
   #added by Ash- admin dashboard does not need to be added, deleted or edited
  resources :admin_dash_board,  :only => :index

end

app/models/unused_listing.rb
# == Schema Information
#
# Table name: unused_listings
#
#  id                    :integer         not null, primary key
#  name                  :string(255)
#  telephone             :string(255)
#  fax                   :string(255)
#  suite                 :string(255)
#  address               :string(255)
#  city                  :string(255)
#  province              :string(255)
#  postal_code           :string(255)
#  latitude              :string(255)
#  longitude             :string(255)
#  business_type         :string(255)
#  sub_type              :string(255)
#  owner                 :string(255)
#  source                :string(255)
#  local_area            :string(255)
#  checked               :boolean
#  menu_collected        :boolean
#  menu_digitized        :boolean
#  menu_in_database      :boolean
#  keep                  :boolean
#  get_menu_from_website :boolean
#  notes                 :text
#  menu_state            :string(255)
#  menu_source           :string(255)
#  created_at            :datetime        not null
#  updated_at            :datetime        not null
#

class UnusedListing < ActiveRecord::Base
end

app/controllers/unused_listings_controller.rb
class UnusedListingsController < ApplicationController
  before_filter :authenticate_user!
  
  def get_all_unused_listings
    @listings_to_be_removed = Listing.where(:keep => false)
  end
  
  def create_unused_listings
    self.get_all_unused_listings
    
    @listings_to_be_removed.each do|listing|
      @unused_listing = UnusedListing.new()
      @unused_listing.name = listing.name
      @unused_listing.telephone = listing.telephone
      @unused_listing.fax = listing.fax
      @unused_listing.suite = listing.suite
      @unused_listing.address = listing.address
      @unused_listing.city = listing.city
      @unused_listing.province = listing.province
      @unused_listing.postal_code = listing.postal_code
      @unused_listing.latitude = listing.latitude
      @unused_listing.longitude = listing.longitude
      @unused_listing.business_type = listing.business_type
      @unused_listing.sub_type = listing.sub_type
      @unused_listing.owner = listing.owner
      @unused_listing.source = listing.source
      @unused_listing.local_area = listing.local_area
      @unused_listing.checked = listing.checked
      @unused_listing.menu_collected = listing.menu_collected
      @unused_listing.menu_digitized = listing.menu_digitized
      @unused_listing.menu_in_database = listing.menu_in_database
      @unused_listing.keep = listing.keep
      @unused_listing.get_menu_from_website = listing.get_menu_from_website
      @unused_listing.notes = listing.notes
      @unused_listing.menu_state = listing.menu_state
      @unused_listing.menu_source = listing.menu_source
      @unused_listing.save
   
    end
    
  end
  
  
  
  
  
  # GET /unused_listings
  # GET /unused_listings.json
  def index
    #self.create_unused_listings
    #Listing.destroy_all(:keep =>false)
    @listings = Listing.all
    @unused_listings = UnusedListing.order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unused_listings }
    end
  end

  # GET /unused_listings/1
  # GET /unused_listings/1.json
  def show
    @unused_listing = UnusedListing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unused_listing }
    end
  end

  # GET /unused_listings/new
  # GET /unused_listings/new.json
  def new
    @unused_listing = UnusedListing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unused_listing }
    end
  end

  # GET /unused_listings/1/edit
  def edit
    @unused_listing = UnusedListing.find(params[:id])
  end

  # POST /unused_listings
  # POST /unused_listings.json
  def create
    @unused_listing = UnusedListing.new(params[:unused_listing])

    respond_to do |format|
      if @unused_listing.save
        format.html { redirect_to @unused_listing, notice: 'Unused listing was successfully created.' }
        format.json { render json: @unused_listing, status: :created, location: @unused_listing }
      else
        format.html { render action: "new" }
        format.json { render json: @unused_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unused_listings/1
  # PUT /unused_listings/1.json
  def update
    @unused_listing = UnusedListing.find(params[:id])

    respond_to do |format|
      if @unused_listing.update_attributes(params[:unused_listing])
        format.html { redirect_to @unused_listing, notice: 'Unused listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unused_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unused_listings/1
  # DELETE /unused_listings/1.json
  def destroy
    @unused_listing = UnusedListing.find(params[:id])
    @unused_listing.destroy

    respond_to do |format|
      format.html { redirect_to unused_listings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/unused_listings_helper.rb
module UnusedListingsHelper
end

app/views/unused_listings/_form.html.erb
<%= simple_form_for(@unused_listing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/unused_listings/edit.html.erb
<h1>Editing unused_listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @unused_listing %> |
<%= link_to 'Back', unused_listings_path %>

app/views/unused_listings/index.html.erb
<h1>Listing unused_listings</h1>
<p>Total number of Unused Listings = <%=@unused_listings.count %></p>
<p>Total number of Listings = <%=@listings.count %></p>
<table id="unused_listings">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>telephone</th>
    <th>fax</th>
    <th>suite</th>
    <th>address</th>
    <th>city</th>
    <th>province</th>
    <th>postal_code</th>
    <th>latitude</th>
    <th>longitude</th>
    <th>business_type</th>
    <th>sub_type</th>
    <th>owner</th>
    <th>source</th>
    <th>local_area</th>
    <th>checked</th>
    <th>menu_collected</th>
    <th>menu_digitized</th>
    <th>menu_in_database</th>
    <th>keep</th>
    <th>get_menu_from_website</th>
    <th>notes</th>
    <th>menu_state</th>
    <th>menu_source</th>
  </tr>

<% @unused_listings.each do |unused_listing| %>
  <tr>
  	<td><%= unused_listing.id %></td>
  	<td><%= unused_listing.name %></td>
  	<td><%= unused_listing.telephone %></td>
  	<td><%= unused_listing.fax %></td>
  	<td><%= unused_listing.suite %></td>
  	<td><%= unused_listing.address %></td>
  	<td><%= unused_listing.city %></td>
  	<td><%= unused_listing.province %></td>
  	<td><%= unused_listing.postal_code %></td>
  	<td><%= unused_listing.latitude %></td>
  	<td><%= unused_listing.longitude %></td>
  	<td><%= unused_listing.business_type %></td>
  	<td><%= unused_listing.sub_type %></td>
  	<td><%= unused_listing.owner %></td>
  	<td><%= unused_listing.source %></td>
  	<td><%= unused_listing.local_area %></td>
  	<td><%= unused_listing.checked %></td>
  	<td><%= unused_listing.menu_collected %></td>
  	<td><%= unused_listing.menu_digitized %></td>
  	<td><%= unused_listing.menu_in_database %></td>
  	<td><%= unused_listing.keep %></td>
  	<td><%= unused_listing.get_menu_from_website %></td>
  	<td><%= unused_listing.notes %></td>
  	<td><%= unused_listing.menu_state %></td>
  	<td><%= unused_listing.menu_source %></td>
  	
  	
    <td><%= link_to 'Show', unused_listing %></td>
    <td><%= link_to 'Edit', edit_unused_listing_path(unused_listing) %></td>
    <td><%= link_to 'Destroy', unused_listing, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unused listing', new_unused_listing_path %>

app/views/unused_listings/new.html.erb
<h1>New unused_listing</h1>

<%= render 'form' %>

<%= link_to 'Back', unused_listings_path %>

app/views/unused_listings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_unused_listing_path(@unused_listing) %> |
<%= link_to 'Back', unused_listings_path %>